logging:
  config: classpath:logging-back-dev.xml
spring:
  redis:
    host: 192.168.0.102
    port: 6379
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.102:3306/cdtudrive?serverTimezone=Asia/Shanghai&useSSL=false&&characterEncoding=utf8&&useAffectedRows=true